### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by LemonHX** [unknownue/vulkan-tutorial-rust#3]
When I trying to build these examples following problem occurs
in utility/platforms.rs line 74 the method not found ```xlib_surface_loader.create_xlib_surface_khr```
it is actually
```xlib_surface_loader.create_xlib_surface```

**Comment by LemonHX** [comment]
also windows in line 133 ```win32_surface_loader.create_win32_surface```

**Comment by LemonHX** [comment]
and in my Windows10 I found this error when I was running 27
```
[Debug] -> " [ VUID-VkSwapchainCreateInfoKHR-minImageCount-01271 ] Object: 0x23cb6da0dc0 (Type = 3) | vkCreateSwapchainKHR() called with minImageCount = 0, which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR() (i.e. minImageCount = 2, maxImageCount = 0). The Vulkan spec states: minImageCount must be greater than or equal to the value returned in the minImageCount member of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-minImageCount-01271)"
thread 'main' panicked at 'Failed to create Swapchain!: Result(-1)', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `target\release\27.exe` (exit code: 101)```

**Comment by LemonHX** [comment]
I changed the code in ```utility/share/mod.rs``` line 354-357 to
```rust
    let image_count =2;
```

**Comment by unknownue** [comment]
Sorry for my late reply.
When changing the ash version from 0.27.2 to 0.28.0, many namings of Vulkan extensions have changed and I forget to test on Linux and Windows.

**Comment by unknownue** [comment]
I am a Chinese developer. You may talk to me in Chinese.

**Comment by LemonHX** [comment]
吼啊,囧国人啊,目前我也在写一本rust的vulkan教程,
可以考虑加我qq:1332127468
(果然git上装霓虹人可以避免被吐槽英语语法

**Comment by unknownue** [comment]
我发送了加qq的请求 验证信息是nue

**Comment by unknownue** [comment]
[Vulkan](https://github.com/Houjuu-Nue/Vulkan)是我写的对[SaschaWillems/Vulkan](https://github.com/SaschaWillems/Vulkan)的Rust实现
大部分基础工作已经写好了
可惜最近拿不出时间写 你可以参考一下
