### ISSUE TITLE
Chalet asset urls are broken

### ISSUE THREAD

**Issue by mhiley** [unknownue/vulkan-tutorial-rust#32]
I think vulkan-tutorial.com has switched to a different model and removed the original chalet assets: see e.g. https://vulkan-tutorial.com/Loading_models

The PR just grabs them from a github repo instead.

Thanks for this awesome repo. I'm trying to get started with Vulkan, but would much rather learn more Rust in the process than C++, so this is perfect for me 😃

**Comment by unknownue** [comment]
Thanks for your PR. It does remind me the model had been changed. I would update corresponding code when I get some time.

**Comment by unknownue** [comment]
When this repo was created, there were not much choices and tools to use vulkan in rust. But things have been changed a lot in recent years.

Now we have many math(much more easy to use than glm), ECS crates, imgui(both in binding or native) and even physics. It's really exciting to see how the community is growing up.

When you have grasped this tutorial, here are some content you may be interested:
- https://hoj-senna.github.io/ashen-aetna/ -- Another vulkan-tutorial, but in rust+ash.
- https://gitlab.com/Friz64/erupt -- Another Vulkan API bindings.
- https://github.com/adrien-ben/imgui-rs-vulkan-renderer -- How to integrate imgui to vulkan+winit.
