### ISSUE TITLE
example 01 crashes on OS X if you close the windows using the red button

### ISSUE THREAD

**Issue by buzmeg** [unknownue/vulkan-tutorial-rust#7]
$ cargo run --bin 01
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/01`
<close window with red button>
Bus error: 10

**Comment by unknownue** [comment]
Everything seems OK on my machine, both in debug and release mode.
Have you tried the latest SDK ?
Press the `ESC` should close the program as well, does it crash when pressing `ESC`?

**Comment by buzmeg** [comment]
Yes, crashes with ESC as well.

**Comment by unknownue** [comment]
There is a [bug issue](https://github.com/KhronosGroup/MoltenVK/issues/584) in MoltenVK v1.1.106 may make the program crash. It should be fixed with the release of SDK v1.1.108.
Have you tried the latest SDK?

**Comment by buzmeg** [comment]
I have not.  Given the pointer, I will try to do so.

**Comment by unknownue** [comment]
Since there is no response for a long time. I would close this issue. If this problem still reproduces, open the issue again.

**Comment by buzmeg** [comment]
Crashing seems to be gone as of vulkansdk 1.1.114.
