### ISSUE TITLE
example 05 crashes on OS X if you close window with red button

### ISSUE THREAD

**Issue by buzmeg** [unknownue/vulkan-tutorial-rust#8]
$ cargo run --bin 05
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/05`
<close window>
Segmentation fault: 11

**Comment by unknownue** [comment]
Same response with #7

**Comment by buzmeg** [comment]
Quite a few of them crash like this.  I wasn't going to report every one as I assume they come from a common cause.

**Comment by unknownue** [comment]
Reduplicate problem of #7. So close this issue.
